// Generated by CoffeeScript 1.5.0
(function() {

  window.Website = {
    "INTERACTIVE MEDIA": {
      "Portfolio": {
        img: "portfolio.jpg",
        slug: "portfolio",
        items: {
          "x-1": "<h2>About My Portfolio</h2>",
          "p-1a": " Welcome to my portfolio, there is a plethora of work that I am proud of on this site so please take your time while browsing.",
          "p-2": "This website has been programmed from the ground up by yours truly. Here's how it's done.",
          "x-2": '<h3>Libraries</h3>',
          "p-3a": 'When coding, you should believe that someone somewhere in the world has probably written the same code already; I\'ve saved myself a lot of time using these libraries to make my ideas a reality.',
          "x-3": '<ul>\
                <li><a href="http://zeptojs.com/" target="_blank">Zepto (jQuery)</a> for HTML DOM manipulation and animation</li>\
                <li><a href="http://necolas.github.io/normalize.css/" target="_blank">Normalize</a> for crossbrowser adaption</li>\
                <li><a href="http://icanhazjs.com/" target="_blank">ICanHaz.js</a> for templating HTML elements</li>\
                <li><a href="http://www.zachleat.com/web/bigtext-makes-text-big/" target="_blank">BigText</a> for large type fitting</li>\
                <li><a href="http://simplefocus.com/flowtype/" target="_blank">flowtype</a> for text readability</li>\
            </ul>',
          "p-4": 'Another useful tool I use is <a href="http://coffeescript.org" target="_blank">coffeescript</a> which is syntax variant of javascript that looks more like Ruby and Python.'
        }
      },
      "RareWire IDE": {
        img: "rarewire.png",
        slug: "rarewire",
        items: {
          "logo-1": "rarewire.png",
          "p-2": "Part-time job at <a href='http://www.rarewire.com/'>RareWire LLC</a>",
          "img-2": "layout.png",
          "img-3": "modals.png",
          "img-4": "start-screen.png",
          "p-4": "Using RareWire's App Creation Studio you can create cross-platform apps for iOS and Android devices using simple XML structured code.",
          "x-1": "<h2>Touch Tabs</h2>",
          "yt-1": "hG_xZ5EzhwY",
          "gh-1": "ZombieHippie/Touch-Tabs-jQuery",
          "p-6": "<br>",
          "x-2": "<h2>Touch Splitter</h2>",
          "if-2": "http://zombiehippie.com/ide",
          "gh-2": "ZombieHippie/Touch-Splitter-jQuery"
        }
      },
      "Foxtrot JS": {
        img: "foxtrot.gif",
        slug: "foxtrot",
        items: {
          "x-1": "<h1>The Foxtrot</h1>",
          "x-2": "<i>DoodleJump inspired HTML5 game</i>",
          "p-1": "This is an HTML5 game made using the CoffeeScript Parser. CoffeeScript is a way of writing JavaScript with code that has a less verbose feel to it. The objective of this game is to climb as high as you can by jumping from platform to platform, some platforms are moving. Each platform will slowly deteriorate as you jump on them which is indicated by the platform's tint.",
          "gh-1": "ZombieHippie/TheFoxtrot",
          "x-3": "<a target=\"_blank\" href=\"http://foxtrot.zombiehippie.com\">Launch Foxtrot in a new window</a>"
        }
      },
      "Freesketch JS": {
        img: "freesketch.png",
        slug: "freesketch",
        items: {
          "x-1": "<h1>FreeSketch</h1>",
          "p-1": "This is an HTML5, WebSockets, and Node js based sketch pad supporting multiple users collaboratively drawing on the SAME \"sketchpad\". The sketch pad is equiped with sliders for stroke-size, color hue, and darkness; tools can be found by pressing the space bar or will be brought up upon typing. Then you can press the ENTER key to send what ever message you had typed up to all clients connected to the server. It is programmed with CoffeeScript being parsed into javascript client side. And the server-side is programmed by way of javascript and node js using the ws library.",
          "gh-1": "ZombieHippie/FreeSketch",
          "x-3": "<a target=\"_blank\" href=\"http://sketch.zombiehippie.com\">Launch FreeSketch in a new window</a>"
        }
      },
      "AS3 Platformer": {
        img: "platformer.gif",
        slug: "platformer",
        items: {
          "x-1": "<h1>AS3 Platformer</h1>",
          "swf-1": "platformer8"
        }
      },
      "AS3 Thrower": {
        img: "thrower.gif",
        slug: "thrower",
        items: {
          "x-1": "<h1>AS3 Thrower Game</h1>",
          "swf-1": "throwergame"
        }
      }
    },
    "ANIMATION": {
      "Toasty": {
        img: "toasty.jpg",
        slug: "toasty",
        items: {
          "x-1": "<h1>Toasty</h1>",
          "yt-1": "yWX1oUNAw9c"
        }
      },
      "Lego Minecraft": {
        img: "minecraftsma.jpg",
        slug: "minecraftsma",
        items: {
          "x-1": "<h1>Lego Minecraft</h1>",
          "yt-1": "EXL3aZ09340"
        }
      },
      "Girl in Hyacinth Blue": {
        img: "hyacinth.jpg",
        slug: "hyacinth",
        items: {
          "x-1": "<h1>Girl in Hyacinth Blue</h1>",
          "yt-1": "Y3k202eiBEM"
        }
      },
      "The Saddest Cloud": {
        img: "saddestcloud.png",
        slug: "saddestcloud",
        items: {
          "x-1": "<h1>The Saddest Cloud</h1>",
          "yt-1": "rpAEAqmL6KU"
        }
      },
      "Post-it Note Show": {
        img: "postitnoteshow.jpg",
        slug: "postitnoteshow",
        items: {
          "x-1": "<h1>Post-it Note Show</h1>",
          "yt-1": "1iR_9hSabLU"
        }
      },
      "Funny Stop Motion": {
        img: "funnysma.jpg",
        slug: "funnysma",
        items: {
          "x-1": "<h1>Funny Stop Motion</h1>",
          "yt-1": "dqe_pDFWiXg"
        }
      }
    },
    "GRAPHIC DESIGN": {
      "NHS Shirt Design": {
        img: "nhsshirt.png",
        slug: "nhsshirt",
        items: {
          "x-1": "<h1>National Honor Society T-Shirt 2014</h1>",
          "img-1": "NHS-Brain-present.png"
        }
      },
      "Robotics Club Branding": {
        img: "roboticsbranding.png",
        slug: "roboticsbranding",
        items: {
          "x-1": "<h1>Robotics Club Branding</h1>",
          "img-1": "business-cards-poster.png",
          "img-2": "viking-robotics-card-horizontal.png",
          "img-3": "viking-robotics-card-vertical.png"
        }
      },
      "Rock4Hope Poster": {
        img: "rock4hope.png",
        slug: "rock4hope",
        items: {
          "x-1": "<h1>Rock4Hope Poster Layout</h1>",
          "img-1": "Rock4Hope2013FlyerV1R5-BRITISH-INVASION.png"
        }
      },
      "Macbeth Poster Design": {
        img: "macbeth.jpg",
        slug: "macbeth",
        items: {
          "x-1": "<h1>Macbeth Poster Design</h1>",
          "img-1": "MacBeth-Final-CS32.png"
        }
      },
      "Robotics Shirt Design": {
        img: "roboticsshirt.png",
        slug: "roboticsshirt",
        items: {
          "x-1": "<h1>Robotics Shirt Design</h1>",
          "img-1": "VikingRobotics.jpg"
        }
      }
    },
    "TRADITIONAL ART": {
      "Portrait Sketches": {
        img: "sally.jpg",
        slug: "sally"
      }
    }
  };

}).call(this);
